<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SuperHeroImage extends Model
{
    /**.
     * @var string
     */
    protected $table = 'superheroes_images';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        parent::deleting(function($model) {
            $path = public_path($model->file);
            if (file_exists($path) && is_file($path)) {
                return unlink($path);
            }
        });
    }
}
